# coding: utf-8

"""
    Проект интернет-магазина

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_products_get(self):
        """Test case for products_get

        Получить список всех товаров  # noqa: E501
        """
        pass

    def test_products_post(self):
        """Test case for products_post

        Добавить товар  # noqa: E501
        """
        pass

    def test_products_product_id_delete(self):
        """Test case for products_product_id_delete

        Удалить товар по ID  # noqa: E501
        """
        pass

    def test_products_product_id_get(self):
        """Test case for products_product_id_get

        Получить информацию о товаре по ID  # noqa: E501
        """
        pass

    def test_products_product_id_put(self):
        """Test case for products_product_id_put

        Изменить информацию о товаре по ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
