# coding: utf-8

"""
    Проект интернет-магазина

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.categories_api import CategoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_category_get(self):
        """Test case for category_get

        Получить список всех категорий  # noqa: E501
        """
        pass

    def test_category_post(self):
        """Test case for category_post

        Добавить новую категорию  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
