# coding: utf-8

"""
    Проект интернет-магазина

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_order_create_post(self):
        """Test case for order_create_post

        Создать заказ на товар  # noqa: E501
        """
        pass

    def test_order_get(self):
        """Test case for order_get

        Получить список всех заказов  # noqa: E501
        """
        pass

    def test_order_order_id_get(self):
        """Test case for order_order_id_get

        Получить информацию о заказе по его ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
