# coding: utf-8

# flake8: noqa

"""
    Проект интернет-магазина

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.categories_api import CategoriesApi
from swagger_client.api.orders_api import OrdersApi
from swagger_client.api.products_api import ProductsApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.category import Category
from swagger_client.models.order import Order
from swagger_client.models.product import Product
