version: "3.8"

services:
  app:
      build: .
      container_name: app
      hostname: app
      restart: unless-stopped
      ports:
        - '8888:8080'
      networks:
        - vm_net

  prometheus:
    image: prom/prometheus
    ports:
      - "9099:9090"
    volumes:
      - ./prometheus:/etc/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - vm_net

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data/:/tmp/tempo
    ports:
      - "14269:14268"  # jaeger ingest
      - "3209:3200"    # tempo
      - "4399:4317"    # otlp grpc
      - "4400:4318"    # otlp http
      - "9412:9411"    # zipkin
#    network_mode: "host"
    healthcheck:
      test: [ "CMD", "grpc", "health", "check" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - vm_net

  loki:
     image: grafana/loki:2.9.0
     ports:
       - "3101:3100"
     volumes:
       - ./loki-config.yaml:/etc/loki-config.yaml
     command: -config.file=/etc/loki-config.yaml
     networks:
       - vm_net

  promtail:
     image: grafana/promtail:2.9.0
     volumes:
       - ./promtail-config.yaml:/etc/promtail-config.yaml
       - ./var/log:/var/log
     command: -config.file=/etc/promtail-config.yaml
     networks:
       - vm_net

  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.94.0
    depends_on:
      - "victoriametrics"
    ports:
      - "8430:8429"
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus.yml:/etc/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/write"
    networks:
      - vm_net
    restart: always

  victoriametrics:
    container_name: rusakov-victoriametrics
    image: victoriametrics/victoria-metrics:v1.94.0
    ports:
      - "18430:8428"
      - "18090:8089"
      - "12004:2003"
      - "14243:4242"
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
    networks:
      - vm_net
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.7
    depends_on:
      - "victoriametrics"
    ports:
      - "3001:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
    networks:
      - vm_net
    restart: always

volumes:
  vmagentdata: {}
  vmdata: {}
  grafanadata: {}
  tempodata: {}

networks:
  vm_net:
