global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'E-catalog'
    static_configs:
      - targets: ['192.168.20.217:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.20.217:9090']

  - job_name: 'vmagent'
    scrape_interval: 5s
    static_configs:
      - targets: ['vmagent:8429']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:9411']