name: Swagger Server and Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-server-and-client:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install server dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install prometheus_client
        pip install prometheus_flask_exporter
        
    - name: Run Swagger Server
      run: |
        cd server
        python -m swagger_server.__main__ &
        
    - name: Install client dependencies  
      run: |
        cd client
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install prometheus_client
        pip install prometheus_flask_exporter
        
    - name: Run Client
      run: |
        cd client
        python main.py
